export default [
  {
    id: 1,
    firstName: 'Anna',
    lastName: 'Ivanova',
    age: 20,
    group: 'P-101',
    gender: 'female',
    email: 'anna.ivanova@university.com',
    grade: 4.8,
    isActive: true,
  },
  {
    id: 2,
    firstName: 'Alexey',
    lastName: 'Petrov',
    age: 22,
    group: 'IT-202',
    gender: 'male',
    email: 'a.petrov@university.com',
    grade: 4.2,
    isActive: true,
  },
  {
    id: 3,
    firstName: 'Maria',
    lastName: 'Sidorova',
    age: 19,
    group: 'B-105',
    gender: 'female',
    email: 'm.sidorova@university.com',
    grade: 5.0,
    isActive: false,
  },
  {
    id: 4,
    firstName: 'Dmitry',
    lastName: 'Smirnov',
    age: 21,
    group: 'P-101',
    gender: 'male',
    email: 'd.smirnov@university.com',
    grade: 4.5,
    isActive: true,
  },
  {
    id: 5,
    firstName: 'Elena',
    lastName: 'Kuznetsova',
    age: 23,
    group: 'IT-202',
    gender: 'female',
    email: 'e.kuznetsova@university.com',
    grade: 4.9,
    isActive: true,
  },
  {
    id: 6,
    firstName: 'Ivan',
    lastName: 'Popov',
    age: 20,
    group: 'B-105',
    gender: 'male',
    email: 'i.popov@university.com',
    grade: 4.1,
    isActive: true,
  },
  {
    id: 7,
    firstName: 'Olga',
    lastName: 'Volkova',
    age: 22,
    group: 'P-101',
    gender: 'female',
    email: 'o.volkova@university.com',
    grade: 4.7,
    isActive: false,
  },
  {
    id: 8,
    firstName: 'Sergey',
    lastName: 'Fedorov',
    age: 19,
    group: 'IT-202',
    gender: 'male',
    email: 's.fedorov@university.com',
    grade: 4.3,
    isActive: true,
  },
];
